version: 0.2

env:
  secrets-manager:
    SECRET_USERNAME: "pipeline-docker-cred:username"
    SECRET_PASSWORD: "pipeline-docker-cred:password"

phases:
  build:
    commands:
    - echo "Hello World from Buildspec.yml"
    - echo "$SECRET_USERNAME"
      
artifacts: 
  files:
    - Dockerfile
